### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: root should have type="object"

### ISSUE THREAD

**Issue by rajani007** [ethlo/jsons2xsd#2]
Running into multiple issues with the attached json. Can you please help me to create xsd. The exception i posted below was addressed by adding type=object but ran into properties issue. Then after fixing that ran into another issue. The attached json is generated by Swagger tool.

Exception in thread "main" java.lang.IllegalArgumentException: root should have type="object"
	at com.ethlo.schematools.jsons2xsd.Assert.isTrue(Assert.java:13)
	at com.ethlo.schematools.jsons2xsd.Jsons2Xsd.convert(Jsons2Xsd.java:81)
	at com.ethlo.schematools.jsons2xsd.TestJsonToXsd.main(TestJsonToXsd.java:21)

[offers.txt](https://github.com/ethlo/jsons2xsd/files/149092/offers.txt)

**Comment by mortenharaldsen** [comment]
Hi,  and thanks for your report.  The file you  have attached is not a json schema,  it is just json data.
