### ISSUE TITLE
Test using your example JSON fails

### ISSUE THREAD

**Issue by rakkatak** [ethlo/jsons2xsd#5]
Hello,

I'm testing your code using your example. Here is my main method:
public static void main(String[] args) {
        try {
            InputStream inputStream = new FileInputStream("C:\projects\acp.convertJsonToXsd\src\testSchema.json");
            Reader inputStreamReader = new InputStreamReader(inputStream);
            final String targetNameSpaceUri = "http://my.example.com/ns";
            final OuterWrapping wrapping = OuterWrapping.TYPE;
            final String name = "mySpecialType";
            final Document xsdDocument = Jsons2Xsd.convert(inputStreamReader, targetNameSpaceUri, wrapping, name);

```
        System.out.println(xsdDocument.toString());
    } catch (IOException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }

}
```

The json is the example you provide.

It seems to error on the required field for email.

Here is the output / exception:
In PROP
In PROP
Exception in thread "main" java.lang.IllegalArgumentException: required must have type: string array
    at com.ethlo.schematools.jsons2xsd.Assert.isTrue(Assert.java:13)
    at com.ethlo.schematools.jsons2xsd.Jsons2Xsd.getRequiredList(Jsons2Xsd.java:397)
    at com.ethlo.schematools.jsons2xsd.Jsons2Xsd.handleObject(Jsons2Xsd.java:281)
    at com.ethlo.schematools.jsons2xsd.Jsons2Xsd.doIterateSingle(Jsons2Xsd.java:213)
    at com.ethlo.schematools.jsons2xsd.Jsons2Xsd.doIterate(Jsons2Xsd.java:174)
    at com.ethlo.schematools.jsons2xsd.Jsons2Xsd.convert(Jsons2Xsd.java:101)
    at acp.convertJsonToXsd.ConvertJsonToXsd.main(ConvertJsonToXsd.java:22)

Please advise. Thank you!

Anita

**Comment by ethlo** [comment]
Thanks for that catch! I will see if I can get the time to update the example soon. In the meantime:  The example is in JSON schema 0.3 which used to have the "required" attribute on a per property basis. In the latest draft, it is a separate attribute "required:['fieldName1', 'fieldName2', ...]"

```javascript
{
	"title": "Example Schema",
	"type": "object",
	"properties": {
		"firstName": {
			"type": "string"
		},
		"lastName": {
			"type": "string"
		},
		"age": {
			"description": "Age in years",
			"type": "integer",
			"minimum": 0
		}
	},
	"required": ["firstName", "lastName"]
}
```
